name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install python venv
        run: |
          cd functions
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy to Firebase Functions
        run: |
          source functions/venv/bin/activate
          firebase deploy --only functions --token ${{secrets.FIREBASE_SERVICE_ACCOUNT_SHOGIAI}}

  deploy_storage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Databases
        run: firebase deploy --only storage,database --token ${{secrets.FIREBASE_SERVICE_ACCOUNT_SHOGIAI}}

  deploy_hosting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd hosting
          npm ci
          npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --non-interactive --only hosting --token ${{secrets.FIREBASE_SERVICE_ACCOUNT_SHOGIAI}}
