name: Linting functions

on: [push]

jobs:
  Formating:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          cd functions
          python -m pip install --upgrade pip
          pip install black

      - name: Check code formatting with Black
        run: |
          cd functions
          black --check $(git ls-files '*.py')

  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          cd functions
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          pylint --rcfile=.pylintrc $(git ls-files '*.py')
