name: Linting hosting

on: [push]

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd hosting
          npm install @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint typescript
          npx eslint .
